angular.module('exModule', []);
angular.module('exModule');
angular.module('exModule').controller('mainController', ['$scope', function($scope){

	$scope.runningestimate = [{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 1 The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision.	More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."
	},

	{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 2 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	},{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 3 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 4 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 5 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 6 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}

	]

	$scope.globalpolitics = [{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 7 The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision.	More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."
	},

	{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 8 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	},{
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 9 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 10 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 11 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}, {
		title: "Hungary Drills Army at Border With Serbia as Migrants Enter",
		preview: "The number of migrants in the area has shown no sign of abating, and Hungarian military officials said the army would help secure the border.",
		content: "BOX 12 - The Hungarian Army was conducting exercises near the border with Serbia on Thursday, a possible prelude to a more active role as thousands of migrants continued to pour into the country overnight.The involvement of the army in policing the border, where a 110-mile fence with razor wire is being constructed to keep migrants out, is subject to the approval of a bill in Parliament this month.The number of migrants in the area has shown no sign of abating, and Hungarian military officials have said the army would help secure the country's borders.	The military exercises came a day after Jean-Claude Juncker, the president of the European Commission, the executive arm of the European Union, called for countries across the 28-nation bloc to set aside divisions to help migrants in a speech that softened attitudes in some quarters but fanned nationalist responses elsewhere. 	Denmark, which had temporarily closed a highway running north from the German border to try to contain migrants seeking to travel on to Sweden and other countries, said on Thursday that it would not impede their progress. Prime Minister Lars Lokke Rasmussen gave his “full support” to the police, who made the decision. More than 3,000 migrants crossed the border into Austria from Hungary overnight, and another 3,000 or so were expected to arrive in the area on Thursday, the police and Red Cross officials at the border said. Rail service was halted between the two countries on Thursday, Reuters reported, because Austria could not handle the huge number of migrants crossing the border. It was not clear when service would resume."

	}

	]

	$scope.setactiveindex = function($index){
		$scope.activeindex = $index;
	}
	$scope.isactiveindex = function($index){
		return ($scope.activeindex === $index);
	}
	$scope.setactiveindex2 = function($index){
		$scope.activeindex2 = $index;
	}
	$scope.isactiveindex2 = function($index){
		return ($scope.activeindex2 === $index);
	}
	$scope.setactiveindex3 = function($index){
		$scope.activeindex2 = -2;
		$scope.activeindex = -2;
	}
	

	
	$scope.setactiveindexgp = function($index){
		$scope.activeindexgp = $index;
	}
	$scope.isactiveindexgp = function($index){
		return ($scope.activeindexgp === $index);
	}
	$scope.setactiveindex2gp = function($index){
		$scope.activeindex2gp = $index;
	}
	$scope.isactiveindex2gp = function($index){
		return ($scope.activeindex2gp === $index);
	}
	$scope.setactiveindex3gp = function($index){
		$scope.activeindex2gp = -2;
		$scope.activeindexgp = -2;
	}

	}])

	// array of objects 

	// $index (inside of ng-repeat)	}
